import { PrismaClient } from '@prisma/client'
import { HeatLevel } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Clean up existing data
  await prisma.orderItem.deleteMany()
  await prisma.order.deleteMany()
  await prisma.cartItem.deleteMany()
  await prisma.wishlistItem.deleteMany()
  await prisma.review.deleteMany()
  await prisma.fundraiserProduct.deleteMany()
  await prisma.fundraiser.deleteMany()
  await prisma.product.deleteMany()
  await prisma.category.deleteMany()
  await prisma.address.deleteMany()
  await prisma.wholesaleAccount.deleteMany()
  await prisma.recipe.deleteMany()
  await prisma.user.deleteMany()

  console.log('🗑️  Cleaned existing data')

  // Create categories
  const mildCategory = await prisma.category.create({
    data: {
      name: 'Mild Salsa',
      slug: 'mild-salsa',
      description: 'Perfect for those who enjoy flavor without the heat. Great for kids and mild palates.',
      metaTitle: 'Mild Salsa - Jose Madrid Salsa',
      metaDescription: 'Discover our mild salsa varieties, perfect for those who prefer flavor without the heat.',
      sortOrder: 1,
    },
  })

  const mediumCategory = await prisma.category.create({
    data: {
      name: 'Medium Salsa',
      slug: 'medium-salsa',
      description: 'The perfect balance of flavor and heat. Our most popular choice for everyday enjoyment.',
      metaTitle: 'Medium Salsa - Jose Madrid Salsa',
      metaDescription: 'Try our medium heat salsa - the perfect balance of flavor and spice.',
      sortOrder: 2,
    },
  })

  const hotCategory = await prisma.category.create({
    data: {
      name: 'Hot Salsa',
      slug: 'hot-salsa',
      description: 'For those who love the heat! Bold flavors with a serious kick that builds with each bite.',
      metaTitle: 'Hot Salsa - Jose Madrid Salsa',
      metaDescription: 'Experience our hot salsa varieties for those who love bold flavors and serious heat.',
      sortOrder: 3,
    },
  })

  const fruitCategory = await prisma.category.create({
    data: {
      name: 'Gourmet & Fruit Salsa',
      slug: 'gourmet-fruit-salsa',
      description: 'Unique gourmet salsas featuring fresh fruits and premium ingredients.',
      metaTitle: 'Gourmet & Fruit Salsa - Jose Madrid Salsa',
      metaDescription: 'Explore our gourmet and fruit salsa collection with unique flavors and premium ingredients.',
      sortOrder: 4,
    },
  })

  console.log('✅ Created categories')

  // Create products
  const products = [
    {
      name: 'Jose Madrid Original Mild',
      slug: 'jose-madrid-original-mild',
      description: 'Our signature mild salsa made with fresh tomatoes, onions, and a perfect blend of spices.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Tomatoes', 'Onions', 'Bell Peppers', 'Garlic', 'Vinegar', 'Salt', 'Spices'],
      price: 7.00,
      compareAtPrice: 10.99,
      sku: 'JMS-MILD-001',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      isFeatured: true,
      images: ['/images/products/mild.webp'],
      featuredImage: '/images/products/mild.webp',
      searchKeywords: ['signature', 'mild', 'original', 'fresh tomatoes'],
    },
    {
      name: 'Clovis Medium Salsa',
      slug: 'clovis-medium-salsa',
      description: 'The Clovis brand introduced Jose Madrid Salsa in 1989. The Clovis Medium salsa originated to serve in Zak\'s Restaurant in Zanesville, Ohio in 1989. It quickly became our flagship salsa, so Clovis Mild and Medium were hence born. The Clovis series of salsas is named after Clovis, New Mexico, the actual birthplace of Jose Madrid.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Tomatoes', 'Onions', 'Garlic', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-002',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/products/clovis-medium.webp'],
      featuredImage: '/images/products/clovis-medium.webp',
      searchKeywords: ['clovis', 'flagship', 'heritage', 'classic'],
    },
    {
      name: 'Original Hot',
      slug: 'original-hot',
      description: 'The Clovis brand introduced Jose Madrid Salsa in 1989. The Clovis Medium salsa originated to serve in Zak\'s Restaurant in Zanesville, Ohio in 1989. It quickly became our flagship salsa, so Clovis Mild and Medium were hence born. The Clovis series of salsas is named after Clovis, New Mexico, the actual birthplace of Jose Madrid.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Tomatoes', 'Jalapeño Peppers', 'Habanero', 'Onions', 'Garlic', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-001',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/hot.webp'],
      featuredImage: '/images/products/hot.webp',
      searchKeywords: ['original', 'hot', 'spicy', 'heat'],
    },
    {
      name: 'Original X Hot',
      slug: 'original-x-hot',
      description: 'X-Hot is Original Hot only hotter! Add the red Cayenne peppers please!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Tomatoes', 'Cayenne Peppers', 'Habanero', 'Onions', 'Garlic', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-002',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/x-hot.webp'],
      featuredImage: '/images/products/x-hot.webp',
      searchKeywords: ['x-hot', 'cayenne', 'spicy', 'heat lovers'],
    },
    {
      name: 'Black Bean Corn Poblano',
      slug: 'black-bean-corn-poblano',
      description: 'Every one I speak to says this salsa tastes like chili. It is in the top three best selling salsas and is a great condiment.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Black Beans', 'Corn', 'Poblano Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-003',
      inventory: 85,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/products/black-bean-corn-poblano-salsa.webp'],
      featuredImage: '/images/products/black-bean-corn-poblano-salsa.webp',
      searchKeywords: ['black bean', 'corn', 'poblano', 'bestseller'],
    },
    {
      name: 'Cherry Chocolate Hot',
      slug: 'cherry-chocolate-hot',
      description: 'Yes, we added habanero to give this some heat! Pure cocoa mixed with cherries combine to make your taste buds dance. Try this as a marinade with your favorite roasting meat, you won\'t be disappointed!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Cherries', 'Cocoa', 'Habanero Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-003',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/cherry-chocolate-hot.webp'],
      featuredImage: '/images/products/cherry-chocolate-hot.webp',
      searchKeywords: ['cherry', 'chocolate', 'hot', 'marinade'],
    },
    {
      name: 'Cherri Mild Salsa',
      slug: 'cherry-mild-salsa',
      description: 'It\'s the Michigan cherries that make Cherry Mild wonderfully sweet and tart. Make a great snack or as a compliment to meats, fish, or vegetables.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Michigan Cherries', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-001',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/products/cherry-mild.webp'],
      featuredImage: '/images/products/cherry-mild.webp',
      searchKeywords: ['cherry', 'fruit', 'sweet', 'michigan'],
    },
    {
      name: 'Chipotle Con Queso',
      slug: 'chipotle-con-queso-salsa',
      description: 'This cheese based dip is best when slightly warmed in a microwave! Made with slices of real cheddar, smoked chipotle peppers, and chunks of tomatoes.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Cheddar Cheese', 'Chipotle Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-004',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/products/chipotle-con-queso.webp'],
      featuredImage: '/images/products/chipotle-con-queso.webp',
      searchKeywords: ['queso', 'cheese', 'chipotle', 'dip'],
    },
    {
      name: 'Chipotle Hot',
      slug: 'chipotle-hot-salsa',
      description: 'Smoked jalapenos are diced and mixed with a blend of thick and chunky tomatoes and spices. If you\'ve ever tried smoking your own jalapenos and enjoy savory and spicy, this one\'s for you!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Smoked Jalapeños', 'Tomatoes', 'Onions', 'Garlic', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-004',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/chipotle-hot.webp'],
      featuredImage: '/images/products/chipotle-hot.webp',
      searchKeywords: ['chipotle', 'smoked', 'hot', 'savory'],
    },
    {
      name: 'Garden Cilantro Salsa Mild',
      slug: 'garden-cilantro-mild-salsa',
      description: 'New Mexico chilies blended with fresh cilantro, tomatoes, jalapenos, onions, and a hint of lime. Cilantro lovers your new favorite salsa is here!',
      heatLevel: HeatLevel.MILD,
      ingredients: ['New Mexico Chilies', 'Fresh Cilantro', 'Tomatoes', 'Jalapeños', 'Onions', 'Lime'],
      price: 7.00,
      sku: 'JMS-MILD-005',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/products/garden-cilantro-salsa-mild.webp'],
      featuredImage: '/images/products/garden-cilantro-salsa-mild.webp',
      searchKeywords: ['garden', 'cilantro', 'mild', 'fresh'],
    },
    {
      name: 'Garden Cilantro Salsa Hot',
      slug: 'garden-cilantro-hot-salsa',
      description: 'New Mexico chilies blended with fresh cilantro, tomatoes, jalapenos, onions, and a hint of lime. Cilantro lovers your new favorite salsa is here!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['New Mexico Chilies', 'Fresh Cilantro', 'Tomatoes', 'Jalapeños', 'Onions', 'Lime'],
      price: 7.00,
      compareAtPrice: 10.99,
      sku: 'JMS-HOT-005',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      isFeatured: true,
      images: ['/images/products/garden-cilantro-salsa-hot.webp'],
      featuredImage: '/images/products/garden-cilantro-salsa-hot.webp',
      searchKeywords: ['garden', 'cilantro', 'hot', 'spicy'],
    },
    {
      name: 'Jamaican Jerk',
      slug: 'jamaican-jerk-salsa',
      description: 'Remember those great times we had in Jamaica? This will bring those memories back! Our recipe for Jamaican Jerk was developed with the aid of a chef from a resort hotel in Jamaica. It\'s a carrot based jerk with 11 spices and two chilies.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Carrots', 'Jamaican Spices', 'Chilies', 'Tomatoes', 'Onions'],
      price: 7.00,
      sku: 'JMS-HOT-006',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/jamaican-jerk.webp'],
      featuredImage: '/images/products/jamaican-jerk.webp',
      searchKeywords: ['jamaican', 'jerk', 'spices', 'caribbean'],
    },
    {
      name: 'Ghost of Clovis',
      slug: 'ghost-of-clovis',
      description: 'The Ghost of Clovis uses the popular Ghost Pepper to give it special flavor. It is known to be very spicy to those who like spicier foods, but it is not as spicy as our Stupid Hot salsa. Try it out!',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Ghost Peppers', 'Tomatoes', 'Onions', 'Garlic', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-006',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/products/ghost-of-clovis.webp'],
      featuredImage: '/images/products/ghost-of-clovis.webp',
      searchKeywords: ['ghost pepper', 'spicy', 'unique'],
    },
    {
      name: 'Mango Mild Salsa',
      slug: 'mango-mild-salsa',
      description: 'Everyone loves the taste of mangoes right? Try chunks of mango with Clovis Medium Spice! Jose Madrid is famous for our slightly sweet fruit salsas.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Mango', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-002',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/products/mango-mild.webp'],
      featuredImage: '/images/products/mango-mild.webp',
      searchKeywords: ['mango', 'fruit', 'mild', 'sweet'],
    },
    {
      name: 'Mango Habanero Salsa',
      slug: 'mango-habanero-salsa',
      description: 'A mix of our popular Mango line of salsas combined with our Habaneros. A surprisingly enjoyable blend of sweet with a little more bite than our other fruit salsas.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Fresh Mango', 'Habanero Peppers', 'Tomatoes', 'Onions', 'Cilantro', 'Lime'],
      price: 7.00,
      compareAtPrice: 11.49,
      sku: 'JMS-HOT-007',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      isFeatured: true,
      images: ['/images/products/mango-habanero.webp'],
      featuredImage: '/images/products/mango-habanero.webp',
      searchKeywords: ['mango', 'habanero', 'fruit', 'hot', 'sweet'],
    },
    {
      name: 'Peach Mild',
      slug: 'peach-mild-salsa',
      description: 'Peach was one of our very first mild salsas! Sweetened slightly with honey. Great for any spread that needs just a little bit of kick to it.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Peaches', 'Honey', 'Tomatoes', 'Onions', 'Cilantro', 'Lime'],
      price: 7.00,
      sku: 'JMS-FRUIT-003',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/products/peach-mild.webp'],
      featuredImage: '/images/products/peach-mild.webp',
      searchKeywords: ['peach', 'fruit', 'mild', 'honey'],
    },
    {
      name: 'Pineapple Mild Salsa',
      slug: 'pineapple-mild-salsa',
      description: 'This salsa has the great taste of pineapple and it and superb texture. Enjoy the slightly sweet and spicy flavor just as a dip or inspire a new omelet recipe.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Pineapple', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-004',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/products/pineapple-mild.webp'],
      featuredImage: '/images/products/pineapple-mild.webp',
      searchKeywords: ['pineapple', 'fruit', 'mild', 'tropical'],
    },
    {
      name: 'Raspberry BBQ Chipotle',
      slug: 'raspberry-bbq-chipotle',
      description: 'We searched all over the US for the quintessential essence of what good BBQ should taste like. Result: There is no clear winner because each region has its own preferences. So we chose the Motor City and spoke to many people and tasted many BBQ\'s to craft Raspberry BBQ Chipotle. Slightly sweet with a rich smoky chipotle flavor and Jose Madrid\'s own special blend of spices.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Raspberries', 'Chipotle Peppers', 'Tomatoes', 'Onions', 'BBQ Spices'],
      price: 7.00,
      sku: 'JMS-HOT-008',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/raspberry-bbq-chipotle.webp'],
      featuredImage: '/images/products/raspberry-bbq-chipotle.webp',
      searchKeywords: ['raspberry', 'bbq', 'chipotle', 'smoky'],
    },
    {
      name: 'Raspberry Mild Salsa',
      slug: 'raspberry-mild-salsa',
      description: 'Jose Madrid is famous for our blend of sweet fruit flavors and a little kick from the heat, and raspberry was the first fruit salsa developed along with the Peach salsa. Raspberry is one of the icons of Jose Madrid Salsa and has won national awards in two countries!',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Raspberries', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-005',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/products/raspberry-mild.webp'],
      featuredImage: '/images/products/raspberry-mild.webp',
      searchKeywords: ['raspberry', 'fruit', 'award winner', 'iconic'],
    },
    {
      name: 'Roasted Garlic & Olives',
      slug: 'roasted-garlic-olives',
      description: 'Fresh roasted garlic cloves, green and black olives, chilies, tomatoes and Jose Madrid spices. Make sure to check out our recipe page as Roasted Garlic & Olives is a favorite for use in cooking.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Roasted Garlic', 'Green Olives', 'Black Olives', 'Tomatoes', 'Chilies'],
      price: 7.00,
      sku: 'JMS-MILD-007',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/products/roasted-garlic-and-olive.webp'],
      featuredImage: '/images/products/roasted-garlic-and-olive.webp',
      searchKeywords: ['garlic', 'olives', 'roasted', 'cooking'],
    },
    {
      name: 'Roasted Pineapple Habanero Hot',
      slug: 'roasted-pineapple-habanero-hot',
      description: 'Made with Verde XX Hot as the base Jose Madrid\'s special spices and fresh, sweet pineapple chunks make this a favorite.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Roasted Pineapple', 'Habanero Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-009',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      isFeatured: true,
      images: ['/images/products/roasted-pineapple-habanero-hot.webp'],
      featuredImage: '/images/products/roasted-pineapple-habanero-hot.webp',
      searchKeywords: ['pineapple', 'habanero', 'hot', 'roasted'],
    },
    {
      name: 'Spanish Verde Mild',
      slug: 'spanish-verde-mild',
      description: 'Spanish Verde features tomatillo tomatoes, a variety that is ripe when it is green. Along with the tomatillos we blend in green chilies, onions, cilantro, lime, and Jose Madrid spices to create a very unique and extremely tasty salsa. Best tomatillo salsa in the US!',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Tomatillos', 'Green Chilies', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-008',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/products/spanish-verde-mild.webp'],
      featuredImage: '/images/products/spanish-verde-mild.webp',
      searchKeywords: ['verde', 'tomatillo', 'mild', 'green'],
    },
    {
      name: 'Spanish Verde Hot',
      slug: 'spanish-verde-hot',
      description: 'Verde Hot has the Verde Mild base, but with Serrano peppers to make it Hot. This is the "Salsa King\'s" favorite salsa. Won best green salsa in the US in Fort Worth, Texas in 2004 at the Salsa Shoot Out.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Tomatillos', 'Serrano Peppers', 'Green Chilies', 'Onions', 'Cilantro', 'Lime'],
      price: 7.00,
      sku: 'JMS-HOT-010',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/spanish-verde-hot.webp'],
      featuredImage: '/images/products/spanish-verde-hot.webp',
      searchKeywords: ['verde', 'hot', 'serrano', 'award winner'],
    },
    {
      name: 'Spanish Verde XX Hot',
      slug: 'spanish-verde-xx-hot',
      description: 'This is what I lovingly call our "Stupid Hot" salsa. Jose Madrid has always been about flavor more than heat alone, but some like it hot. Twenty one years ago, we sold in Toronto Canada at beer and wine festivals. Each time, people would say there wasn\'t a salsa hot enough for them. Challenge accepted! You can thank the birth of Stupid Hot Salsa at Jose Madrid to Toronto.',
      heatLevel: HeatLevel.EXTRA_HOT,
      ingredients: ['Tomatillos', 'Super Hot Peppers', 'Serrano Peppers', 'Onions', 'Cilantro', 'Lime'],
      price: 7.00,
      sku: 'JMS-XHOT-001',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/spanish-verde-xx-hot.webp'],
      featuredImage: '/images/products/spanish-verde-xx-hot.webp',
      searchKeywords: ['stupid hot', 'xx hot', 'extreme heat', 'extra hot'],
    },
    {
      name: 'Strawberry Mild',
      slug: 'strawberry-mild',
      description: 'Made with Clovis Mild as a base and added special Jose Madrid spices along with fresh, sweet strawberry chunks.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Strawberries', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-006',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      isFeatured: true,
      images: ['/images/products/raspberry-mild.webp'],
      featuredImage: '/images/products/raspberry-mild.webp',
      searchKeywords: ['strawberry', 'fruit', 'mild', 'sweet'],
    },
    {
      name: 'Cherry Hot',
      slug: 'cherry-hot',
      description: 'Specially Crafted for the UC Health Fundraiser, but it was so good that we decided to keep making it! The tart sweetness of Cherries with the heat of the Habanero Pepper...It\'s a MUST TRY.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Cherries', 'Habanero Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-011',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/cherry-chocolate-hot.webp'],
      featuredImage: '/images/products/cherry-chocolate-hot.webp',
      searchKeywords: ['cherry', 'hot', 'sweet tart', 'habanero'],
    },
    {
      name: 'Green Apple',
      slug: 'green-apple',
      description: 'Perfect condiment for Turkey or Pork. Little sweet, little heat.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Green Apples', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-007',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/products/ghost-of-clovis.webp'],
      featuredImage: '/images/products/ghost-of-clovis.webp',
      searchKeywords: ['apple', 'fruit', 'condiment', 'turkey', 'pork'],
    },
    {
      name: 'Ghost of Clovis Hot',
      slug: 'ghost-of-clovis-hot',
      description: 'The Ghost of Clovis uses the popular Ghost Pepper to give it special flavor. It is known to be very spicy to those who like spicier foods, but it is not as spicy as our Stupid Hot salsa. Try it out!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Ghost Peppers', 'Tomatoes', 'Onions', 'Garlic', 'Habanero', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-012',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/products/ghost-of-clovis.webp'],
      featuredImage: '/images/products/ghost-of-clovis.webp',
      searchKeywords: ['ghost pepper', 'hot', 'spicy', 'unique'],
    },
  ]

  for (const productData of products) {
    await prisma.product.create({
      data: productData,
    })
  }

  console.log('✅ Created products')

  // Create admin user
  const adminUser = await prisma.user.create({
    data: {
      email: 'admin@josemadridsalsa.com',
      name: 'Jose Madrid',
      role: 'ADMIN',
      isEmailVerified: true,
      phone: '740-521-4304',
    },
  })

  // Create sample customer
  const customer = await prisma.user.create({
    data: {
      email: 'customer@example.com',
      name: 'John Customer',
      role: 'CUSTOMER',
      isEmailVerified: true,
      phone: '555-123-4567',
    },
  })

  // Create customer address
  await prisma.address.create({
    data: {
      userId: customer.id,
      type: 'BOTH',
      firstName: 'John',
      lastName: 'Customer',
      street: '123 Main Street',
      city: 'Columbus',
      state: 'OH',
      zipCode: '43215',
      country: 'US',
      phone: '555-123-4567',
      isDefault: true,
    },
  })

  console.log('✅ Created users and addresses')

  // Create sample fundraiser
  await prisma.fundraiser.create({
    data: {
      name: 'Spring Band Fundraiser',
      slug: 'spring-band-fundraiser',
      description: 'Help support our school band program by purchasing delicious Jose Madrid Salsa!',
      organizationName: 'Springfield High School Band',
      contactEmail: 'band@springfieldhs.edu',
      contactPhone: '555-987-6543',
      startDate: new Date('2024-03-01'),
      endDate: new Date('2024-04-30'),
      goal: 5000.00,
      commissionRate: 40.00, // 40% commission
      status: 'ACTIVE',
      isActive: true,
    },
  })

  console.log('✅ Created sample fundraiser')

  // Create sample analytics data
  await prisma.analytics.createMany({
    data: [
      {
        type: 'PAGE_VIEW',
        page: '/',
        sessionId: 'session_001',
        country: 'US',
        region: 'OH',
        city: 'Columbus',
      },
      {
        type: 'PRODUCT_VIEW',
        page: '/salsas/jose-madrid-medium-salsa',
        category: 'product',
        label: 'jose-madrid-medium-salsa',
        sessionId: 'session_001',
        country: 'US',
        region: 'OH',
        city: 'Columbus',
      },
      {
        type: 'ADD_TO_CART',
        page: '/salsas/jose-madrid-medium-salsa',
        category: 'ecommerce',
        action: 'add_to_cart',
        label: 'jose-madrid-medium-salsa',
        value: 1,
        sessionId: 'session_001',
        country: 'US',
        region: 'OH',
        city: 'Columbus',
      },
    ],
  })

  console.log('✅ Created sample analytics')

  // Create recipes
  const recipes = [
    {
      title: 'Chile Colorado (Mexican Beef Stew)',
      slug: 'chile-colorado-mexican-beef-stew',
      description: 'Chunks of beef chuck and Roasted Garlic & Olives Salsa - roast until tender. Delicious!',
      category: 'Main Course',
      difficulty: 'Medium',
      prepTime: '20 min',
      cookTime: '120 min',
      servings: 4,
      featured: true,
      featuredImage: '/images/recipes/Roasted-Garlic-Bruschetta.jpg',
      ingredients: ['Chunks of beef chuck', '1 jar José Madrid Roasted Garlic & Olives Salsa'],
      instructions: ['Cut beef chuck into chunks.', 'Combine beef with Roasted Garlic & Olives Salsa.', 'Roast until tender.'],
    },
    {
      title: 'Chipotlé White Cheddar Mashed Potatoes',
      slug: 'chipotle-white-cheddar-mashed-potatoes',
      description: 'Creamy mashed potatoes elevated with smoky chipotle salsa and white cheddar cheese.',
      category: 'Side Dish',
      difficulty: 'Easy',
      prepTime: '15 min',
      cookTime: '25 min',
      servings: 6,
      featured: false,
      featuredImage: '/images/recipes/White-Cheddar-Mashed-Potatoes.jpg',
      ingredients: ['3-1/2 pounds Russet potatoes, peeled, cut into 1-inch pieces', '2/3 cup of milk', '1 cup of cheddar cheese', '4 tablespoons butter (optional)', '3 tablespoons José Madrid Chipotlé Salsa'],
      instructions: ['Cook potatoes in boiling salted water until very tender. Drain.', 'Add Cheddar Cheese, Butter, and Milk.', 'Using an electric mixer, beat until smooth.', 'Stir in José Madrid Chipotlé Salsa.', 'Season to taste with salt and pepper. Sprinkle with parsley.'],
    },
    {
      title: 'Raspberry Chicken',
      slug: 'raspberry-chicken',
      description: 'Tender baked chicken breasts served with raspberry salsa over rice for a sweet and savory combination.',
      category: 'Main Course',
      difficulty: 'Easy',
      prepTime: '10 min',
      cookTime: '45 min',
      servings: 4,
      featured: true,
      featuredImage: '/images/recipes/Rasperry-Chicken.jpg',
      ingredients: ['1 12 oz. jar José Madrid Raspberry Salsa', '4 skinless chicken breasts', '2 cups cooked rice'],
      instructions: ['Preheat the oven to 350 degrees.', 'Place the chicken breasts in a baking dish. Add approximately 1 inch of water.', 'To tenderize the chicken, poke holes in the chicken breasts.', 'Bake for 45 minutes.', 'When chicken is ready, top the cooked rice with raspberry salsa.'],
    },
    {
      title: 'José Madrid\'s Stupid Three Bean Southwestern Dip',
      slug: 'jose-madrids-stupid-three-bean-southwestern-dip',
      description: 'A hearty and flavorful three-bean dip perfect for parties, made with black beans, pinto beans, and garbanzo beans.',
      category: 'Appetizer',
      difficulty: 'Easy',
      prepTime: '15 min',
      cookTime: '0 min',
      servings: 8,
      featured: false,
      featuredImage: '/images/recipes/Three-Bean-Bean-Dip.webp',
      ingredients: ['1 14 oz. can of black beans, drained', '1 14 oz. can pinto beans, drained', '1 14 oz. can garbanzo beans, drained', '3-4 medium sized tomatoes diced', '1 large red onion diced', '1 16 oz. package of frozen corn kernels, thawed, drained', '½ bunch of cilantro finely chopped', '1 13 oz. jar José Madrid Salsa (your choice of flavor)'],
      instructions: ['Combine all beans, diced tomatoes, red onion, corn, and cilantro in a large bowl.', 'Add José Madrid Salsa of your choice.', 'Refrigerate for 2-3 hours or overnight.', 'Serve with tortilla chips.'],
    },
    {
      title: 'Peach Salsa Queso Dip',
      slug: 'peach-salsa-queso-dip',
      description: 'A warm, creamy dip combining peach salsa with cream cheese and spicy sausage.',
      category: 'Appetizer',
      difficulty: 'Easy',
      prepTime: '10 min',
      cookTime: '15 min',
      servings: 6,
      featured: false,
      featuredImage: '/images/recipes/peach-salsa.jpg',
      ingredients: ['1 12 oz. jar José Madrid Peach Salsa', '2 10 oz. packages cream cheese', '1 package of spicy sausage'],
      instructions: ['Place the cream cheese in a mixing bowl; allow to soften while you fry the sausage.', 'After you fry the sausage, drain the grease and add the sausage to the cream cheese.', 'Add José Madrid Peach Salsa and hand mix.', 'Microwave on high for 2 minutes. Remove, stir, and repeat until cheese is completely melted.', 'Serve with José Madrid\'s white corn tortilla chips.'],
    },
    {
      title: 'Spanish Verdé Potato Omelet',
      slug: 'spanish-verde-potato-omelet',
      description: 'A hearty Spanish-style omelet with potatoes and Spanish Verdé salsa, perfect for breakfast or dinner.',
      category: 'Main Course',
      difficulty: 'Medium',
      prepTime: '15 min',
      cookTime: '15 min',
      servings: 4,
      featured: true,
      featuredImage: '/images/recipes/spanish-verde-potato-omelet.jpg',
      ingredients: ['1 12 oz. jar of José Madrid Spanish Verdé (Mild, Hot or XX Hot)', '6 eggs', '1/2 teaspoon salt', '1/3 cup milk', '1/4 stick butter or olive oil', '2 small potatoes, peeled & quartered', '3 oz. Feta or Monterey Jack cheese (optional)'],
      instructions: ['Sauté the potatoes in butter or olive oil for 8-10 minutes over low to medium heat.', 'Place eggs, milk and salt in a bowl; whisk thoroughly, then pour over the potatoes.', 'Cook over low heat, tilting the pan and lifting the cooked edges to allow the uncooked portion to run underneath until the eggs begin to set.', 'While eggs are still runny, sprinkle with cheese and 6-8 tablespoons of José Madrid Verdé salsa.', 'Set under preheated broiler for 1 minute. Cut into 4 sections and serve.'],
    },
    {
      title: 'José\'s Favorite Clovis Chili',
      slug: 'joses-favorite-clovis-chili',
      description: 'A hearty and flavorful chili featuring José Madrid Clovis salsa, ground beef, and kidney beans.',
      category: 'Main Course',
      difficulty: 'Easy',
      prepTime: '15 min',
      cookTime: '120 min',
      servings: 6,
      featured: false,
      featuredImage: '/images/recipes/chili-con-queso.jpg',
      ingredients: ['1 12 oz. jar of José Madrid Clovis', '1 lb. of coarsely ground beef', '1 16 oz. can of tomato sauce', '2 16 oz. cans of red kidney beans', '1 cup water'],
      instructions: ['Cook meat over high heat until meat loses color. Drain the grease.', 'Combine meat, water, beans, tomato sauce and José Madrid Clovis Salsa in chili pot.', 'Simmer for 2 hours, stirring occasionally.', 'Double the recipe and you will be ready for the next day!'],
    },
    {
      title: 'Taco Salad',
      slug: 'taco-salad',
      description: 'A delicious layered taco salad featuring Clovis chili, fresh vegetables, and José Madrid salsa.',
      category: 'Main Course',
      difficulty: 'Easy',
      prepTime: '15 min',
      cookTime: '0 min',
      servings: 4,
      featured: false,
      featuredImage: '/images/recipes/taco-salad.jpg',
      ingredients: ['White Corn Tortilla Chips', 'Shredded lettuce', 'José\'s Favorite Clovis Chili recipe', 'Diced tomatoes', 'Diced onions', 'Sour cream', 'José Madrid\'s Original Mild, Medium, or Hot Red Salsas'],
      instructions: ['In a shallow pan, spread the shredded lettuce to create a generous layer.', 'Top with José Madrid\'s White Corn Tortilla Chips.', 'Arrange the remaining ingredients on top in this order: Clovis Chili recipe, tomato, onions and sour cream.'],
    },
    {
      title: 'Zesty Meatloaf',
      slug: 'zesty-meatloaf',
      description: 'A flavorful meatloaf enhanced with Roasted Garlic & Olive Salsa and traditional seasonings.',
      category: 'Main Course',
      difficulty: 'Easy',
      prepTime: '15 min',
      cookTime: '45 min',
      servings: 6,
      featured: false,
      featuredImage: '/images/recipes/Zesty-Tomato-Glazed-Meatloaf.jpg',
      ingredients: ['2 lbs. lean ground beef', '1/4 cup José Madrid\'s Roasted Garlic & Olive Salsa', '1/2 cup oats (May substitute crushed crackers or bread crumbs)', '1 tablespoon Worcestershire sauce', '2 large eggs'],
      instructions: ['Preheat oven to 350 degrees.', 'In a large mixing bowl, combine ground beef, salsa, oats, Worcestershire sauce, and eggs.', 'In the center of a 9" x 13" pan, shape the beef mixture into a loaf.', 'Top with more Roasted Garlic & Olive Salsa.', 'Bake for 45 minutes or until done.'],
    },
    {
      title: 'Tex-Mex Shepherd\'s Pie',
      slug: 'tex-mex-shepherds-pie',
      description: 'A Southwestern twist on the classic shepherd\'s pie with chicken, black beans, and José Madrid salsa.',
      category: 'Main Course',
      difficulty: 'Medium',
      prepTime: '20 min',
      cookTime: '20 min',
      servings: 6,
      featured: true,
      featuredImage: '/images/recipes/tex-mex-shepherds-pie.webp',
      ingredients: ['8 oz. cooked diced chicken', '1 cup José Madrid\'s Salsa', '1 cup drained black beans', '1 18 oz. package frozen mashed potatoes (thawed)', '½ cup (packed) shredded Monterey Pepper Jack Cheese', '3 Tablespoons chopped fresh cilantro'],
      instructions: ['Preheat oven to 450°.', 'Combine chicken, Salsa, and beans in a 9-inch-diameter glass pie dish; stir to blend well.', 'Spoon potatoes atop filling in pie dish, covering completely.', 'Sprinkle with cheese and half the cilantro.', 'Bake casserole until filling is bubbling, cheese melts and potatoes are beginning to brown, about 20 minutes.', 'Sprinkle with remaining cilantro and serve.'],
    },
    {
      title: 'Roasted Garlic and Olive Pasta Sauté',
      slug: 'roasted-garlic-and-olive-pasta-saute',
      description: 'A rich and flavorful pasta dish featuring Roasted Garlic and Olive salsa with heavy cream.',
      category: 'Main Course',
      difficulty: 'Easy',
      prepTime: '10 min',
      cookTime: '15 min',
      servings: 4,
      featured: false,
      featuredImage: '/images/recipes/Roasted-Garlic-Bruschetta.jpg',
      ingredients: ['6 oz. José Madrid\'s Roasted Garlic and Olive Salsa', '2-3 oz. Heavy Cream', 'Desired pasta', 'Parmesan or mozzarella cheese'],
      instructions: ['Combine José Madrid\'s Roasted Garlic and Olive Salsa and heavy cream in a heavy saucepan.', 'On medium to high heat allow them to reduce while desired pasta is cooking in boiling water, about 10-15 minutes.', 'Once pasta is done, drain, and add to sauté pan.', 'Toss the pasta with the Roasted Garlic and Olive reduction.', 'Top with parmesan or mozzarella, and serve.'],
    },
    {
      title: 'José Madrid\'s Chipotlé Potato Salad',
      slug: 'jose-madrids-chipotle-potato-salad',
      description: 'A smoky and flavorful potato salad with bacon, broccoli, and chipotle salsa dressing.',
      category: 'Side Dish',
      difficulty: 'Easy',
      prepTime: '20 min',
      cookTime: '25 min',
      servings: 8,
      featured: false,
      featuredImage: '/images/recipes/chipotle-potato-salad-recipe.jpg',
      ingredients: ['3 lbs cooked, diced and cooled redskin potatoes', '12 oz. cooked crisp bacon chopped', '1 head of trimmed broccoli spears', '½ cup chopped red onion', '2 cups (packed) shredded cheddar', '½ cup sour cream', '½ cup mayo', '3 oz. José Madrid\'s Chipotle Salsa'],
      instructions: ['Cook and dice potatoes, then let cool.', 'Cook bacon until crisp and chop.', 'Combine potatoes, bacon, broccoli, onion, and cheddar cheese in a large bowl.', 'To make the dressing, mix equal amounts of sour cream and mayo.', 'Add José Madrid\'s Chipotle Salsa to the sour cream and mayo dressing.', 'Coat the potato mixture with dressing, chill and serve.'],
    },
    {
      title: 'José Madrid\'s Roasted Garlic and Olive Bruschettas',
      slug: 'jose-madrids-roasted-garlic-and-olive-bruschettas',
      description: 'Quick and easy appetizer featuring toasted baguette slices topped with Roasted Garlic and Olive salsa.',
      category: 'Appetizer',
      difficulty: 'Easy',
      prepTime: '10 min',
      cookTime: '10 min',
      servings: 6,
      featured: false,
      featuredImage: '/images/recipes/Roasted-Garlic-Bruschetta.jpg',
      ingredients: ['1 whole baguette sliced ½ inch thick on the bias', 'José Madrid\'s Roasted Garlic and Olive Salsa', 'Goat cheese or shredded mozzarella'],
      instructions: ['Toast the sliced bread on a cookie sheet in the oven.', 'When finished let cool.', 'Spread toast with José Madrid\'s Roasted Garlic and Olive Salsa.', 'Top with goat cheese or shredded mozzarella.', 'Place the toast back in the oven to melt the cheese and serve.'],
    },
    {
      title: 'José Madrid\'s Chili Con Queso',
      slug: 'jose-madrids-chili-con-queso',
      description: 'A spicy and creamy cheese dip perfect for parties, made with Spanish Verdé and melted cheddar.',
      category: 'Appetizer',
      difficulty: 'Medium',
      prepTime: '15 min',
      cookTime: '20 min',
      servings: 8,
      featured: true,
      featuredImage: '/images/recipes/chili-con-queso.jpg',
      ingredients: ['¼ cup plus 2 Tablespoons (3/4 Stick) butter', '1 large onion, chopped', '¼ cup plus 2 Tablespoons all-purpose flour', '1 28 oz. can peeled tomatoes, drained, chopped', '4 oz. José Madrid\'s Spanish Verdé', '12 oz. shredded Cheddar', 'José Madrid\'s Original Hot Salsa', 'José Madrid\'s White Corn Tortilla Chips'],
      instructions: ['Sauté chopped onion in butter in heavy saucepan.', 'Stir in flour. Continue to cook flour until golden brown.', 'Add José Madrid\'s Verdé Salsa, tomatoes, and cook until mixture thickens.', 'Add cheddar and stir until melted and bubbling.', 'Season with José Madrid\'s Original Hot Salsa.', 'Transfer to chafing dish or fondue pot.', 'Serve with white corn tortilla chips.'],
    },
    {
      title: 'José Madrid\'s Chipotlé Steamed Mussels with Coconut Milk',
      slug: 'jose-madrids-chipotle-steamed-mussels-with-coconut-milk',
      description: 'An elegant seafood dish featuring fresh mussels steamed in coconut milk and chipotle salsa.',
      category: 'Seafood',
      difficulty: 'Medium',
      prepTime: '15 min',
      cookTime: '20 min',
      servings: 4,
      featured: false,
      featuredImage: '/images/recipes/chipotle-potato-salad-recipe.jpg',
      ingredients: ['2 Tablespoons Vegetable oil', '½ cup chopped carrot', '½ cup chopped celery', '1 14oz. can unsweetened coconut milk', '1 cup chicken stock', '1 cup dry white wine', '4-5 oz. José Madrid\'s Chipotlé Salsa', '2 ½ pounds of Mussels scrubbed and debearded'],
      instructions: ['Heat oil in heavy large pot over medium heat.', 'Add carrot and celery and sauté until tender.', 'Stir in coconut milk, wine, chicken stock; bring to a boil over high heat to reduce to 2 cups, about 15 minutes.', 'Stir in José Madrid\'s Chipotlé.', 'Add mussels, cover and cook until mussels open, about 5 minutes.', 'Transfer mussels to large bowl and serve. (Discard any mussels that do not open.)'],
    },
    {
      title: 'José Madrid\'s Southwestern Caesar Salad with Chipotlé Dressing',
      slug: 'jose-madrids-southwestern-caesar-salad-with-chipotle-dressing',
      description: 'A Southwestern twist on classic Caesar salad featuring a smoky chipotle dressing.',
      category: 'Salad',
      difficulty: 'Easy',
      prepTime: '15 min',
      cookTime: '0 min',
      servings: 4,
      featured: false,
      featuredImage: '/images/recipes/Roasted-Garlic-Bruschetta.jpg',
      ingredients: ['½ cup mayonnaise', '1 ½ tablespoon canned low-salt chicken broth', '1 Tablespoon soy sauce', '1 Tablespoon fresh lime juice', '1 teaspoon brown sugar', '2 oz. José Madrid Chipotlé Salsa', '1 large head of Romaine Lettuce, cut into bite size pieces', '2 medium tomatoes diced', '½ cup frozen corn kernels, thawed, drained', '4 Tablespoons freshly grated Parmesan cheese'],
      instructions: ['Whisk mayonnaise, chicken broth, soy sauce, lime juice, brown sugar and José Madrid\'s Chipotlé Salsa in small bowl to blend completely.', 'Dressing can be prepared a day ahead of time and held covered in the refrigerator.', 'Prepare in large serving bowl: romaine lettuce, diced tomatoes, corn, and Parmesan cheese.', 'Mix with dressing thoroughly add more Parmesan if desired.', 'Season with salt and pepper to taste and serve!'],
    },
  ]

  for (const recipeData of recipes) {
    await prisma.recipe.create({
      data: recipeData,
    })
  }

  console.log('✅ Created recipes')
  console.log('🌱 Database has been seeded successfully!')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })