import { PrismaClient, HeatLevel } from '@prisma/client'
import bcrypt from 'bcryptjs'
// Recipes are loaded statically on pages, database seeding removed
// import { recipeData } from './data/recipes'

const prisma = new PrismaClient()

export async function seedDatabase() {
  // Clean up existing data
  await prisma.orderItem.deleteMany()
  await prisma.order.deleteMany()
  await prisma.cartItem.deleteMany()
  await prisma.wishlistItem.deleteMany()
  await prisma.review.deleteMany()
  await prisma.fundraiserProduct.deleteMany()
  await prisma.fundraiser.deleteMany()
  await prisma.product.deleteMany()
  await prisma.category.deleteMany()
  await prisma.address.deleteMany()
  await prisma.wholesaleAccount.deleteMany()
  await prisma.recipe.deleteMany()
  await prisma.user.deleteMany()

  console.log('🗑️  Cleaned existing data')

  // Create categories
  const mildCategory = await prisma.category.create({
    data: {
      name: 'Mild Salsa',
      slug: 'mild-salsa',
      description: 'Perfect for those who enjoy flavor without the heat. Great for kids and mild palates.',
      metaTitle: 'Mild Salsa - Jose Madrid Salsa',
      metaDescription: 'Discover our mild salsa varieties, perfect for those who prefer flavor without the heat.',
      sortOrder: 1,
    },
  })

  const mediumCategory = await prisma.category.create({
    data: {
      name: 'Medium Salsa',
      slug: 'medium-salsa',
      description: 'The perfect balance of flavor and heat. Our most popular choice for everyday enjoyment.',
      metaTitle: 'Medium Salsa - Jose Madrid Salsa',
      metaDescription: 'Try our medium heat salsa - the perfect balance of flavor and spice.',
      sortOrder: 2,
    },
  })

  const hotCategory = await prisma.category.create({
    data: {
      name: 'Hot Salsa',
      slug: 'hot-salsa',
      description: 'For true heat lovers who enjoy an authentic spicy kick with their salsa.',
      metaTitle: 'Hot Salsa - Jose Madrid Salsa',
      metaDescription: 'Experience our hot salsa varieties for those who love authentic heat.',
      sortOrder: 3,
    },
  })

  const fruitCategory = await prisma.category.create({
    data: {
      name: 'Fruit Salsa',
      slug: 'fruit-salsa',
      description: 'Sweet and tangy fruit-based salsas perfect for a unique flavor experience.',
      metaTitle: 'Fruit Salsa - Jose Madrid Salsa',
      metaDescription: 'Discover our sweet and tangy fruit salsa varieties.',
      sortOrder: 4,
    },
  })

  console.log('✅ Created categories')

  // Create products
  const products = [
    {
      name: 'Jose Madrid Original Mild',
      slug: 'jose-madrid-original-mild',
      description: 'Our signature mild salsa made with fresh tomatoes, onions, and a perfect blend of spices.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Tomatoes', 'Onions', 'Bell Peppers', 'Garlic', 'Vinegar', 'Salt', 'Spices'],
      price: 7.00,
      compareAtPrice: 10.99,
      sku: 'JMS-MILD-001',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      isFeatured: true,
      images: ['/images/new-products/mild.png'],
      featuredImage: '/images/new-products/mild.png',
      searchKeywords: ['signature', 'mild', 'original', 'fresh tomatoes'],
    },
    {
      name: 'Clovis Medium Salsa',
      slug: 'clovis-medium-salsa',
      description: 'The Clovis brand introduced Jose Madrid Salsa in 1989. The Clovis Medium salsa originated to serve in Zak\'s Restaurant in Zanesville, Ohio in 1989. It quickly became our flagship salsa, so Clovis Mild and Medium were hence born. The Clovis series of salsas is named after Clovis, New Mexico, the actual birthplace of Jose Madrid.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Tomatoes', 'Onions', 'Garlic', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-002',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/new-products/clovis-medium.png'],
      featuredImage: '/images/new-products/clovis-medium.png',
      searchKeywords: ['clovis', 'flagship', 'heritage', 'classic'],
    },
    {
      name: 'Original Hot',
      slug: 'original-hot',
      description: 'The Clovis brand introduced Jose Madrid Salsa in 1989. The Clovis Medium salsa originated to serve in Zak\'s Restaurant in Zanesville, Ohio in 1989. It quickly became our flagship salsa, so Clovis Mild and Medium were hence born. The Clovis series of salsas is named after Clovis, New Mexico, the actual birthplace of Jose Madrid.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Tomatoes', 'Jalapeño Peppers', 'Habanero', 'Onions', 'Garlic', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-001',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/hot.png'],
      featuredImage: '/images/new-products/hot.png',
      searchKeywords: ['original', 'hot', 'spicy', 'heat'],
    },
    {
      name: 'Original X Hot',
      slug: 'original-x-hot',
      description: 'X-Hot is Original Hot only hotter! Add the red Cayenne peppers please!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Tomatoes', 'Cayenne Peppers', 'Habanero', 'Onions', 'Garlic', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-002',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/x-hot.png'],
      featuredImage: '/images/new-products/x-hot.png',
      searchKeywords: ['x-hot', 'cayenne', 'spicy', 'heat lovers'],
    },
    {
      name: 'Black Bean Corn Poblano',
      slug: 'black-bean-corn-poblano',
      description: 'Every one I speak to says this salsa tastes like chili. It is in the top three best selling salsas and is a great condiment.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Black Beans', 'Corn', 'Poblano Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-003',
      inventory: 85,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/new-products/black-bean-corn-poblano.png'],
      featuredImage: '/images/new-products/black-bean-corn-poblano.png',
      searchKeywords: ['black bean', 'corn', 'poblano', 'bestseller'],
    },
    {
      name: 'Cherry Chocolate Hot',
      slug: 'cherry-chocolate-hot',
      description: 'Yes, we added habanero to give this some heat! Pure cocoa mixed with cherries combine to make your taste buds dance. Try this as a marinade with your favorite roasting meat, you won\'t be disappointed!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Cherries', 'Cocoa', 'Habanero Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-003',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/cherry-chocolate-hot.png'],
      featuredImage: '/images/new-products/cherry-chocolate-hot.png',
      searchKeywords: ['cherry', 'chocolate', 'hot', 'marinade'],
    },
    {
      name: 'Cherri Mild Salsa',
      slug: 'cherry-mild-salsa',
      description: 'It\'s the Michigan cherries that make Cherry Mild wonderfully sweet and tart. Make a great snack or as a compliment to meats, fish, or vegetables.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Michigan Cherries', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-001',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/new-products/cherry-mild.png'],
      featuredImage: '/images/new-products/cherry-mild.png',
      searchKeywords: ['cherry', 'fruit', 'sweet', 'michigan'],
    },
    {
      name: 'Chipotle Con Queso',
      slug: 'chipotle-con-queso-salsa',
      description: 'This cheese based dip is best when slightly warmed in a microwave! Made with slices of real cheddar, smoked chipotle peppers, and chunks of tomatoes.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Cheddar Cheese', 'Chipotle Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-004',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/new-products/chipotle-con-queso.png'],
      featuredImage: '/images/new-products/chipotle-con-queso.png',
      searchKeywords: ['queso', 'cheese', 'chipotle', 'dip'],
    },
    {
      name: 'Chipotle Hot',
      slug: 'chipotle-hot-salsa',
      description: 'Smoked jalapenos are diced and mixed with a blend of thick and chunky tomatoes and spices. If you\'ve ever tried smoking your own jalapenos and enjoy savory and spicy, this one\'s for you!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Smoked Jalapeños', 'Tomatoes', 'Onions', 'Garlic', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-004',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/chipotle-hot.png'],
      featuredImage: '/images/new-products/chipotle-hot.png',
      searchKeywords: ['chipotle', 'smoked', 'hot', 'savory'],
    },
    {
      name: 'Garden Cilantro Salsa Mild',
      slug: 'garden-cilantro-mild-salsa',
      description: 'New Mexico chilies blended with fresh cilantro, tomatoes, jalapenos, onions, and a hint of lime. Cilantro lovers your new favorite salsa is here!',
      heatLevel: HeatLevel.MILD,
      ingredients: ['New Mexico Chilies', 'Fresh Cilantro', 'Tomatoes', 'Jalapeños', 'Onions', 'Lime'],
      price: 7.00,
      sku: 'JMS-MILD-005',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/new-products/garden-cilantro-salsa-mild.png'],
      featuredImage: '/images/new-products/garden-cilantro-salsa-mild.png',
      searchKeywords: ['garden', 'cilantro', 'mild', 'fresh'],
    },
    {
      name: 'Garden Cilantro Salsa Hot',
      slug: 'garden-cilantro-hot-salsa',
      description: 'New Mexico chilies blended with fresh cilantro, tomatoes, jalapenos, onions, and a hint of lime. Cilantro lovers your new favorite salsa is here!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['New Mexico Chilies', 'Fresh Cilantro', 'Tomatoes', 'Jalapeños', 'Onions', 'Lime'],
      price: 7.00,
      compareAtPrice: 10.99,
      sku: 'JMS-HOT-005',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      isFeatured: true,
      images: ['/images/new-products/garden-cilantro-salsa-hot.png'],
      featuredImage: '/images/new-products/garden-cilantro-salsa-hot.png',
      searchKeywords: ['garden', 'cilantro', 'hot', 'spicy'],
    },
    {
      name: 'Jamaican Jerk',
      slug: 'jamaican-jerk-salsa',
      description: 'Remember those great times we had in Jamaica? This will bring those memories back! Our recipe for Jamaican Jerk was developed with the aid of a chef from a resort hotel in Jamaica. It\'s a carrot based jerk with 11 spices and two chilies.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Carrots', 'Jamaican Spices', 'Chilies', 'Tomatoes', 'Onions'],
      price: 7.00,
      sku: 'JMS-HOT-006',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/jamaican-jerk.png'],
      featuredImage: '/images/new-products/jamaican-jerk.png',
      searchKeywords: ['jamaican', 'jerk', 'spices', 'caribbean'],
    },
    {
      name: 'Ghost of Clovis',
      slug: 'ghost-of-clovis',
      description: 'The Ghost of Clovis uses the popular Ghost Pepper to give it special flavor. It is known to be very spicy to those who like spicier foods, but it is not as spicy as our Stupid Hot salsa. Try it out!',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Ghost Peppers', 'Tomatoes', 'Onions', 'Garlic', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-006',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/new-products/ghost-clovis.png'],
      featuredImage: '/images/new-products/ghost-clovis.png',
      searchKeywords: ['ghost pepper', 'spicy', 'unique'],
    },
    {
      name: 'Mango Mild Salsa',
      slug: 'mango-mild-salsa',
      description: 'Everyone loves the taste of mangoes right? Try chunks of mango with Clovis Medium Spice! Jose Madrid is famous for our slightly sweet fruit salsas.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Mango', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-002',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/new-products/mango-mild.png'],
      featuredImage: '/images/new-products/mango-mild.png',
      searchKeywords: ['mango', 'fruit', 'mild', 'sweet'],
    },
    {
      name: 'Mango Habanero Salsa',
      slug: 'mango-habanero-salsa',
      description: 'A mix of our popular Mango line of salsas combined with our Habaneros. A surprisingly enjoyable blend of sweet with a little more bite than our other fruit salsas.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Fresh Mango', 'Habanero Peppers', 'Tomatoes', 'Onions', 'Cilantro', 'Lime'],
      price: 7.00,
      compareAtPrice: 11.49,
      sku: 'JMS-HOT-007',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      isFeatured: true,
      images: ['/images/new-products/mango-habanero.png'],
      featuredImage: '/images/new-products/mango-habanero.png',
      searchKeywords: ['mango', 'habanero', 'fruit', 'hot', 'sweet'],
    },
    {
      name: 'Peach Mild',
      slug: 'peach-mild-salsa',
      description: 'Peach was one of our very first mild salsas! Sweetened slightly with honey. Great for any spread that needs just a little bit of kick to it.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Peaches', 'Honey', 'Tomatoes', 'Onions', 'Cilantro', 'Lime'],
      price: 7.00,
      sku: 'JMS-FRUIT-003',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/new-products/peach-mild.png'],
      featuredImage: '/images/new-products/peach-mild.png',
      searchKeywords: ['peach', 'fruit', 'mild', 'honey'],
    },
    {
      name: 'Pineapple Mild Salsa',
      slug: 'pineapple-mild-salsa',
      description: 'This salsa has the great taste of pineapple and it and superb texture. Enjoy the slightly sweet and spicy flavor just as a dip or inspire a new omelet recipe.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Pineapple', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-004',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/new-products/pineapple-mild.png'],
      featuredImage: '/images/new-products/pineapple-mild.png',
      searchKeywords: ['pineapple', 'fruit', 'mild', 'tropical'],
    },
    {
      name: 'Raspberry BBQ Chipotle',
      slug: 'raspberry-bbq-chipotle',
      description: 'We searched all over the US for the quintessential essence of what good BBQ should taste like. Result: There is no clear winner because each region has its own preferences. So we chose the Motor City and spoke to many people and tasted many BBQ\'s to craft Raspberry BBQ Chipotle. Slightly sweet with a rich smoky chipotle flavor and Jose Madrid\'s own special blend of spices.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Raspberries', 'Chipotle Peppers', 'Tomatoes', 'Onions', 'BBQ Spices'],
      price: 7.00,
      sku: 'JMS-HOT-008',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/raspberry-bbq-chipotle.png'],
      featuredImage: '/images/new-products/raspberry-bbq-chipotle.png',
      searchKeywords: ['raspberry', 'bbq', 'chipotle', 'smoky'],
    },
    {
      name: 'Raspberry Mild Salsa',
      slug: 'raspberry-mild-salsa',
      description: 'Jose Madrid is famous for our blend of sweet fruit flavors and a little kick from the heat, and raspberry was the first fruit salsa developed along with the Peach salsa. Raspberry is one of the icons of Jose Madrid Salsa and has won national awards in two countries!',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Raspberries', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-005',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/new-products/raspberry-mild.png'],
      featuredImage: '/images/new-products/raspberry-mild.png',
      searchKeywords: ['raspberry', 'fruit', 'award winner', 'iconic'],
    },
    {
      name: 'Roasted Garlic & Olives',
      slug: 'roasted-garlic-olives',
      description: 'Fresh roasted garlic cloves, green and black olives, chilies, tomatoes and Jose Madrid spices. Make sure to check out our recipe page as Roasted Garlic & Olives is a favorite for use in cooking.',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Roasted Garlic', 'Green Olives', 'Black Olives', 'Tomatoes', 'Chilies'],
      price: 7.00,
      sku: 'JMS-MILD-007',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/new-products/roasted-garlic-olives.png'],
      featuredImage: '/images/new-products/roasted-garlic-olives.png',
      searchKeywords: ['garlic', 'olives', 'roasted', 'cooking'],
    },
    {
      name: 'Roasted Pineapple Habanero Hot',
      slug: 'roasted-pineapple-habanero-hot',
      description: 'Made with Verde XX Hot as the base Jose Madrid\'s special spices and fresh, sweet pineapple chunks make this a favorite.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Roasted Pineapple', 'Habanero Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-009',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      isFeatured: true,
      images: ['/images/new-products/roasted-pineapple.jpeg'],
      featuredImage: '/images/new-products/roasted-pineapple.jpeg',
      searchKeywords: ['pineapple', 'habanero', 'hot', 'roasted'],
    },
    {
      name: 'Spanish Verde Mild',
      slug: 'spanish-verde-mild',
      description: 'Spanish Verde features tomatillo tomatoes, a variety that is ripe when it is green. Along with the tomatillos we blend in green chilies, onions, cilantro, lime, and Jose Madrid spices to create a very unique and extremely tasty salsa. Best tomatillo salsa in the US!',
      heatLevel: HeatLevel.MILD,
      ingredients: ['Tomatillos', 'Green Chilies', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-MILD-008',
      inventory: 100,
      weight: 16.0,
      categoryId: mildCategory.id,
      images: ['/images/new-products/spaish-verde-mild.jpeg'],
      featuredImage: '/images/new-products/spaish-verde-mild.jpeg',
      searchKeywords: ['verde', 'tomatillo', 'mild', 'green'],
    },
    {
      name: 'Spanish Verde Hot',
      slug: 'spanish-verde-hot',
      description: 'Verde Hot has the Verde Mild base, but with Serrano peppers to make it Hot. This is the "Salsa King\'s" favorite salsa. Won best green salsa in the US in Fort Worth, Texas in 2004 at the Salsa Shoot Out.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Tomatillos', 'Serrano Peppers', 'Green Chilies', 'Onions', 'Cilantro', 'Lime'],
      price: 7.00,
      sku: 'JMS-HOT-010',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/spanish-verde-hot.jpeg'],
      featuredImage: '/images/new-products/spanish-verde-hot.jpeg',
      searchKeywords: ['verde', 'hot', 'serrano', 'award winner'],
    },
    {
      name: 'Spanish Verde XX Hot',
      slug: 'spanish-verde-xx-hot',
      description: 'This is what I lovingly call our "Stupid Hot" salsa. Jose Madrid has always been about flavor more than heat alone, but some like it hot. Twenty one years ago, we sold in Toronto Canada at beer and wine festivals. Each time, people would say there wasn\'t a salsa hot enough for them. Challenge accepted! You can thank the birth of Stupid Hot Salsa at Jose Madrid to Toronto.',
      heatLevel: HeatLevel.EXTRA_HOT,
      ingredients: ['Tomatillos', 'Super Hot Peppers', 'Serrano Peppers', 'Onions', 'Cilantro', 'Lime'],
      price: 7.00,
      sku: 'JMS-XHOT-001',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/spanish-verde-xx-hot.jpeg'],
      featuredImage: '/images/new-products/spanish-verde-xx-hot.jpeg',
      searchKeywords: ['stupid hot', 'xx hot', 'extreme heat', 'extra hot'],
    },
    {
      name: 'Strawberry Mild',
      slug: 'strawberry-mild',
      description: 'Made with Clovis Mild as a base and added special Jose Madrid spices along with fresh, sweet strawberry chunks.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Fresh Strawberries', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-006',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      isFeatured: true,
      images: ['/images/new-products/strawberry-mild.jpeg'],
      featuredImage: '/images/new-products/strawberry-mild.jpeg',
      searchKeywords: ['strawberry', 'fruit', 'mild', 'sweet'],
    },
    {
      name: 'Cherry Hot',
      slug: 'cherry-hot',
      description: 'Specially Crafted for the UC Health Fundraiser, but it was so good that we decided to keep making it! The tart sweetness of Cherries with the heat of the Habanero Pepper...It\'s a MUST TRY.',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Cherries', 'Habanero Peppers', 'Tomatoes', 'Onions', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-011',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/cherry-hot.png'],
      featuredImage: '/images/new-products/cherry-hot.png',
      searchKeywords: ['cherry', 'hot', 'sweet tart', 'habanero'],
    },
    {
      name: 'Green Apple',
      slug: 'green-apple',
      description: 'Perfect condiment for Turkey or Pork. Little sweet, little heat.',
      heatLevel: HeatLevel.FRUIT,
      ingredients: ['Green Apples', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Spices'],
      price: 7.00,
      sku: 'JMS-FRUIT-007',
      inventory: 100,
      weight: 16.0,
      categoryId: fruitCategory.id,
      images: ['/images/new-products/green-apple.png'],
      featuredImage: '/images/new-products/green-apple.png',
      searchKeywords: ['apple', 'fruit', 'condiment', 'turkey', 'pork'],
    },
    {
      name: 'Ghost of Clovis Hot',
      slug: 'ghost-of-clovis-hot',
      description: 'The Ghost of Clovis uses the popular Ghost Pepper to give it special flavor. It is known to be very spicy to those who like spicier foods, but it is not as spicy as our Stupid Hot salsa. Try it out!',
      heatLevel: HeatLevel.HOT,
      ingredients: ['Ghost Peppers', 'Tomatoes', 'Onions', 'Garlic', 'Habanero', 'Spices'],
      price: 7.00,
      sku: 'JMS-HOT-012',
      inventory: 100,
      weight: 16.0,
      categoryId: hotCategory.id,
      images: ['/images/new-products/ghost-clovis.png'],
      featuredImage: '/images/new-products/ghost-clovis.png',
      searchKeywords: ['ghost pepper', 'hot', 'spicy', 'unique'],
    },
  ]

  for (const product of products) {
    await prisma.product.create({ data: product })
  }

  console.log('✅ Created products')

  // Create admin user
  const hashedPassword = await bcrypt.hash('admin123', 10)
  await prisma.user.create({
    data: {
      email: 'admin@josemadrid.net',
      name: 'Admin User',
      password: hashedPassword,
      role: 'ADMIN',
      isEmailVerified: true,
    },
  })

  console.log('✅ Created admin user')

  // Recipes are loaded statically on pages - no database seeding needed
  console.log('✅ Skipped recipe seeding (loaded statically)')

  return {
    categories: 4,
    products: products.length,
    recipes: 0, // Recipes loaded statically from files
    users: 1,
  }
}
