export const ACCEPTED_FILE_EXTENSIONS = [
  '.md',
  '.txt',
  '.doc',
  '.docx',
  '.pdf',
  '.csv',
  '.tsv',
  '.xlsx',
  '.xslx',
  '.xls',
  '.rtf',
  '.json',
  '.html',
  '.htm',
  '.markdown',
  '.mdx',
  '.epub',
  '.jpg',
  '.jpeg',
  '.png',
  '.gif',
  '.bmp',
  '.tiff',
]

export const ACCEPTED_MIME_TYPES = [
  'text/plain',
  'text/markdown',
  'text/csv',
  'text/tab-separated-values',
  'text/html',
  'application/json',
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/rtf',
  'application/epub+zip',
  'image/jpeg',
  'image/png',
  'image/gif',
  'image/bmp',
  'image/tiff',
]

export const TRAINING_MAX_CHARACTERS = 120_000
